project:
  title: "DIY CGM"
  type: book
  output-dir: _book

website:
  page-footer:
    left: "Personal Science <https://personalscience.com>"
    right:
      - icon: github
        href: https://github.com/personalscience/diycgmbook
      - icon: twitter
        href: https://twitter.com/sprague

book:
  title: "DIY CGM"
  author: "Personal Science"
  subtitle: "Practical techniques to apply scientific principles to your own life."
  description: "How to do your own personal science experiments with continuous glucose monitoring."
  date: last-modified
  downloads: [epub, docx]
  output-file: diycgm
  chapters:
    - part: "General Overview"
      chapters:
        - index.md
        - "Projects/Personal Science/PS-CGM/Introduction.md"
        - "Projects/Personal Science/PS-CGM/How to get your CGM.md"
        - "Projects/Personal Science/PS-CGM/News and Experiences.md"
    - part: "Techniques"
      chapters:
        - "Projects/Personal Science/PS-CGM/Diet and food-tracking.md"
        - "Projects/Personal Science/PS-CGM/Using Your CGM Data.md"
        - "Projects/Personal Science/PS-CGM/Advanced Topics.md"
    - References.qmd

bibliography:
  - book.bib

extract-media: "assets/images"
license: "MIT"


format:
  html:
    theme: literata
    toc: true
    css: css/theme.css
  epub:
    css: css/normalize.css
  docx:
    toc: true
    number-sections: true
    highlight-style: github

editor: visual
